#! /usr/bin/env python

from Assembler import *

################################################################################
# This is a simple assembler that generates machine code for the Hack Platform. 
# See examples folder for some programs.
#
# Created by Geoff Gardner. 
################################################################################


# entry point. 
if __name__ == "__main__":
	import sys

	if len(sys.argv) < 2:
		print "Usage: ./HackAssembler <filename> -[f/o]"
		print "\tO: Output verbatim"
		print "\tF: Write to file"
		sys.exit()

	a = Assembler(sys.argv[1])
	a.assemble()
	if set([i.lower().find("-o") for i in sys.argv]) != set([-1]):
		a.output()
	if set([i.lower().find("-f") for i in sys.argv]) != set([-1]):
		a.writetofile()

	del a
	sys.exit()